[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"
extend-select = ["I"]

[pytest]
pythonpath = "."
testpaths = "./tests"
addopts = "-ra"